; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; Enable PSRAM (Required for AI-Thinker ESP32-CAM resolution/JPEG quality)
build_flags =
    -D BOARD_HAS_PSRAM

; Configure partition scheme to allow large application sizes (Huge APP)
board_build.partitions = huge_app.
monitor_rts = 0
monitor_dtr = 0